# Network protocols

class _Request:
    """Should only be generated by NetworkProtocol class"""

    def __init__(self, code, args):
        self.code = code
        self.args = args


class Protocol:
    ENCODING = 'utf-8'
    SEPARATOR = '\r\n'
    REQUESTS = (
        SEND_MSG := 'SEND',
        CHECK_ADMIN := 'ISADMIN',
        KICK := 'KICK',
        MUTE := 'MUTE',
        UNMUTE := 'UNMUTE',
        BAN := 'BAN',
        UNBAN := 'UNBAN'
    )
    RESPONSES = (

    )

    @classmethod
    def parse(cls, msg: bytes):
        msg = msg.decode(cls.ENCODING)
        parts = msg.split(cls.SEPARATOR)
        if len(parts) != 2 or parts[0] not in cls.REQUESTS:
            return None
        return _Request(parts[0], parts[1])
